/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface ChunkOptions {
  minLength?: number
  maxLength?: number
  phase?: number
  title?: string
}
export interface Chunk {
  level: number
  header?: string
  headers: Array<string | undefined | null>
  breadcrumb: string
  text: string
  length: number
}
export declare function chunk(inputs: Array<Buffer | string>, options?: ChunkOptions | undefined | null): Promise<Array<Array<Chunk>>>
export declare function chunkSync(inputs: Array<Buffer | string>, options?: ChunkOptions | undefined | null): Array<Array<Chunk>>
