/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function chunk(inputs: Array<Buffer | string>, options?: ChunkOptions | undefined | null): Promise<Array<Array<Chunk>>>

export interface Chunk {
  level: number
  header?: string
  headers: Array<string | undefined | null>
  breadcrumb: string
  text: string
  length: number
}

export interface ChunkOptions {
  minLength?: number
  maxLength?: number
  phase?: number
  title?: string
}
