// prettier-ignore
/* eslint-disable */
// @ts-nocheck
/* auto-generated by NAPI-RS */

const { existsSync } = require('fs')
const { join } = require('path')

const { platform, arch } = process

const platformMap = {
  'darwin x64': 'breadchunks.darwin-x64.node',
  'darwin arm64': 'breadchunks.darwin-arm64.node',
  'linux x64': 'breadchunks.linux-x64-gnu.node',
  'linux arm64': 'breadchunks.linux-arm64-gnu.node',
  'win32 x64': 'breadchunks.win32-x64-msvc.node',
}

let nativeBinding = null
let loadError = null

const localFile = platformMap[`${platform} ${arch}`]

if (localFile && existsSync(join(__dirname, localFile))) {
  try {
    nativeBinding = require(join(__dirname, localFile))
  } catch (err) {
    loadError = err
  }
}

if (!nativeBinding) {
  try {
    nativeBinding = require('./breadchunks.node')
  } catch (err) {
    loadError = loadError || err
  }
}

if (!nativeBinding) {
  throw new Error(`Failed to load breadchunks native module. Platform: ${platform} ${arch}\n${loadError}`)
}

module.exports = nativeBinding
module.exports.chunk = nativeBinding.chunk
module.exports.chunkSync = nativeBinding.chunkSync
